"""Deterministic analysis primitives shared by PROOF execution surfaces."""

from proof_core.canonical_json import (
    CanonicalJsonError,
    canonical_json_bytes,
    content_digest,
)
from proof_core.configuration import (
    CONFIGURATION_SCHEMA_VERSION,
    DEFAULT_CONFIGURATION_PATH,
    DEFAULT_FAIL_ON,
    DEFAULT_SCOPE,
    ConfigurationError,
    ConfigurationLimits,
    EffectiveScanConfiguration,
    ScanConfigurationOverrides,
    load_local_scan_configuration,
    load_scan_configuration,
    match_specifications,
    resolve_local_scan_configuration,
    resolve_scan_configuration,
)
from proof_core.input_closure import (
    DocumentLimits,
    InputClosure,
    InputClosureError,
    InputFile,
    InputLimits,
    InputManifest,
    InputResource,
    RepositoryDocument,
    build_input_closure,
    build_input_manifest,
    parse_repository_document,
    read_repository_document,
    read_repository_resource,
)
from proof_core.operation_normalization import (
    CLASSIFIER_VERSION,
    OPERATION_VIEW_SCHEMA_VERSION,
    AgentPolicy,
    NormalizationIssue,
    NormalizedOperation,
    NormalizedParameter,
    NormalizedResponse,
    OperationSet,
    RiskSignal,
    SecurityRequirement,
    SecuritySchemeRequirement,
    normalize_operations,
    tokenize_risk_text,
)
from proof_core.validator_client import (
    ValidatorDiagnostic,
    ValidatorResult,
    WorkerFailure,
    WorkerLimits,
    validate_openapi,
)

__all__ = [
    "CanonicalJsonError",
    "canonical_json_bytes",
    "content_digest",
    "CONFIGURATION_SCHEMA_VERSION",
    "DEFAULT_CONFIGURATION_PATH",
    "DEFAULT_FAIL_ON",
    "DEFAULT_SCOPE",
    "ConfigurationError",
    "ConfigurationLimits",
    "EffectiveScanConfiguration",
    "ScanConfigurationOverrides",
    "load_scan_configuration",
    "load_local_scan_configuration",
    "match_specifications",
    "resolve_scan_configuration",
    "resolve_local_scan_configuration",
    "DocumentLimits",
    "InputClosure",
    "InputClosureError",
    "InputFile",
    "InputLimits",
    "InputManifest",
    "InputResource",
    "RepositoryDocument",
    "build_input_closure",
    "build_input_manifest",
    "parse_repository_document",
    "read_repository_document",
    "read_repository_resource",
    "ValidatorDiagnostic",
    "ValidatorResult",
    "WorkerFailure",
    "WorkerLimits",
    "validate_openapi",
    "CLASSIFIER_VERSION",
    "OPERATION_VIEW_SCHEMA_VERSION",
    "AgentPolicy",
    "NormalizationIssue",
    "NormalizedOperation",
    "NormalizedParameter",
    "NormalizedResponse",
    "OperationSet",
    "RiskSignal",
    "SecurityRequirement",
    "SecuritySchemeRequirement",
    "normalize_operations",
    "tokenize_risk_text",
]

__version__ = "0.1.0"
